### ISSUE TITLE
out of memory on 4G GPU memory

### ISSUE THREAD

**Issue by jasam-sheja** [multimodallearning/pytorch-mask-rcnn#13]
Thanks for the great work!
When running the provided demo I encounter out of memory runtime error.

My machine is Linux with Nvidia 1050 that has 4GB of memory, cuda 9.1, cudnn 7.1 and torch 0.4

error output is:
```
/path-to/pytorch-mask-rcnn/model.py:1474: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
/path-to/pytorch-mask-rcnn/model.py:1595: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  molded_images = Variable(molded_images, volatile=True)
THCudaCheck FAIL file=/path-to/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "demo.py", line 74, in <module>
    results = model.detect([image])
  File "/path-to/pytorch-mask-rcnn/model.py", line 1598, in detect
    detections, mrcnn_mask = self.predict([molded_images, image_metas], mode='inference')
  File "/path-to/pytorch-mask-rcnn/model.py", line 1636, in predict
    [p2_out, p3_out, p4_out, p5_out, p6_out] = self.fpn(molded_images)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 371, in __call__
    result = self.forward(*input, **kwargs)
  File "/path-to/pytorch-mask-rcnn/model.py", line 181, in forward
    p2_out = self.P2_conv1(c2_out) + F.upsample(p3_out, scale_factor=2)
RuntimeError: cuda runtime error (2) : out of memory at /path-to/pytorch/aten/src/THC/generic/THCStorage.cu:58
```
I managed to bypass the problem by using `with torch.no_grad(): ` around variables that use `volatile` flag according to [https://discuss.pytorch.org/t/torch-no-grad/12296](https://discuss.pytorch.org/t/torch-no-grad/12296), but I have no idea what are the repercussions to doing so (newbie to pytorch).

**Comment by rcampos92** [comment]
Try reducing the batch size, I'm using a 12GB GPU and I've used almost 7.4GB using the default configuration. I would like to know if this code supports Multiple GPUs.

**Comment by lasseha** [comment]
@jasam-sheja using `with torch.no_grad()` together with the newest pytorch version is fine for inference. Still, 4GB wont be sufficient for training the model.

@rcampos92 @hli2020 implemented a multi-gpu version based on this repository. Follow issue #19.
