### ISSUE TITLE
The number of anchors per pixel may be wrong?

### ISSUE THREAD

**Issue by wp8619** [multimodallearning/pytorch-mask-rcnn#17]
In line1452, model.py,   

self.rpn = RPN(len(config.RPN_ANCHOR_RATIOS), config.RPN_ANCHOR_STRIDE, 256)

should be 

self.rpn = RPN(len(config.RPN_ANCHOR_RATIOS)*len(config. RPN_ANCHOR_SCALES), config.RPN_ANCHOR_STRIDE, 256) ?

**Comment by hli2020** [comment]
No. the anchors in this repo are placed at difference scales in the FPN network. Each pixel on a certain scale (feature map) has only one scale; different aspect ratios. You can of course do as you suggested (which is done by other detectors.)

**Comment by wp8619** [comment]
Thanks for the explanation. It indeed is like what you said. @hli2020
