### ISSUE TITLE
several issues

### ISSUE THREAD

**Issue by pfjaeger** [multimodallearning/pytorch-mask-rcnn#4]
Hi,
first of all thanks for the implementation.
I encountered some issues which i would like to report:
1) I believe the FPN, RPN, classifier,  and mask nets all are missing a .cuda()
so that would be lines 1456, 1468, 1471, 1474 in model.py. If you dont do this an error occurs sayin the weights are not not in a GPUTensor. Or am I missing something?

2) The way you do sequential batch sizing leads to always batch size one, because gradients are deleted **before** the last batch sample:

```
if (batch_count % self.config.BATCH_SIZE) == 0:
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm(self.parameters(), 5.0)
            if (batch_count % self.config.BATCH_SIZE) == 0:
                optimizer.step()
                batch_count = 0
```

If you would do optimizer.zero_grad() after the optimizer.step() this would allow for batch_sizes > 1 to be updated. Again, please correct me if I am wrong.

3) the matterport version trains much faster and better than this implementation - on my problem. Especially the RPN. Have there been any changes w.r.t matterport which were not mentioned yet?

**Comment by pfjaeger** [comment]
Regarding my 3rd point from the previous message, i solved the issue. Training didn't work because you are using a different weight initialization than matterport. This can be fixed by replacing line 1502 in model.py by:

```
if isinstance(m, nn.Conv2d):
    xavier_uniform(m.weight)
```

**Comment by lasseha** [comment]
Hi,

thanks for your remarks.

1. I cant reproduce the error on my machine, but explicitly moving all submodules to GPU should not be necessary. The pytorch [docs](http://pytorch.org/docs/master/nn.html#torch.nn.Module) state that cuda() is called recursively on all registered submodules. So, calling model = model.cuda() as in line 45 in demo.py should be sufficient.

2. Yes, you are definitely right. The zero_grad() operation should follow after step(). Following [this](https://discuss.pytorch.org/t/how-to-implement-accumulated-gradient/3822/12) discussion i am also not sure if maybe the learning rate need to be adjusted to resemble the matterport training schedule.

3. Not intentionally but there may be mistakes/differences and i'm glad you found one.

**Comment by hao522** [comment]
Why do we use sequential batch sizing here? Because of limited images per GPU?

**Comment by hao522** [comment]
Does it support multi-gpu training yet?

**Comment by hao522** [comment]
@pfjaeger @lasseha  have you tried training the model for a long time? I encountered a problem that in the middle of training, the program crashes with the error "cuda out of memory", this normally happens at around 1k to 4k steps.  And I observed the gpu usage started from around 6GB at first step to 11GB later, seems to me that there's some variable free problems

**Comment by hao522** [comment]
@John1231983  some gpu memory occupation is not probably freed. Haven't trained from scratch yet,  there's not resnet101 weights provided

**Comment by John1231983** [comment]
I have error when training so I did not use this repo

**Comment by hao522** [comment]
@John1231983  what are the errors? which repo are you using right now?

**Comment by lasseha** [comment]
@hao522 I trained the network for more than 100 epochs without a memory problem on a GTX 1070 with 8 GB. Did you find the part where variable memory is not freed? If so, please let us know.

**Comment by hao522** [comment]
@lasseha it was caused somewhere inside the valid_epoch() function, after I remove the validation step during training, the problem never happened again. BTW, have you successfully trained the network from scratch yet (without using keras converted weights)?

**Comment by hao522** [comment]
@lasseha Did you train the network from scratch, how was the result?

**Comment by lasseha** [comment]
Unfortunately, the training from scratch is about 8 percent worse than the matterport results. I assume there is either still something wrong in the code or i did not find the right training schedule yet.

**Comment by pfjaeger** [comment]
I trained from scratch, with the changes i reported i get the same performance as with matterport. I am not training on COCO though, but my own data set.

**Comment by hao522** [comment]
do you mean 8 percent on coco?

**Comment by lasseha** [comment]
@pfjaeger glad to hear that.

@hao522 Then the difference of 8 percent on COCO is most likely due to a not optimal training schedule. Unfortunately, training on COCO on one GPU is very time consuming making it difficult to optimize the schedule.
