### ISSUE TITLE
what do ['arch'] means for?

### ISSUE THREAD

**Issue by LaiPiXiong** [multimodallearning/pytorch-mask-rcnn#54]
When I run 'nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=[arch]', it show info as follows:
nvcc fatal   : Value '[arch]' is not defined for option 'gpu-architecture'
I don't know what is ['arch'], what can I do for this?

**Comment by BYJRK** [comment]
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list
