### ISSUE TITLE
Unable to build roialign

### ISSUE THREAD

**Issue by LaiPiXiong** [multimodallearning/pytorch-mask-rcnn#55]
I run code as follows:
`cd roialign/roi_align/src/cuda/
 nvcc -c -o crop_and_resize_kernel.cu.o crop_and_resize_kernel.cu -x cu -Xcompiler -fPIC -arch=[arch]
 cd ../../
 python build.py
and it comes out an error`
----------------------------------------------------Error Shows------------------------------------------------------------
Including CUDA code.
/home/mohong/workspace/pytorch-mask-rcnn/roialign/roi_align
generating /tmp/tmpHfqKxT/_crop_and_resize.c
setting the current directory to '/tmp/tmpHfqKxT'
running build_ext
building '_crop_and_resize' extension
creating home
creating home/mohong
creating home/mohong/workspace
creating home/mohong/workspace/pytorch-mask-rcnn
creating home/mohong/workspace/pytorch-mask-rcnn/roialign
creating home/mohong/workspace/pytorch-mask-rcnn/roialign/roi_align
creating home/mohong/workspace/pytorch-mask-rcnn/roialign/roi_align/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _crop_and_resize.c -o ./_crop_and_resize.o -std=c99 -fopenmp -std=c99
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c /home/mohong/workspace/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.c -o ./home/mohong/workspace/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.o -std=c99 -fopenmp -std=c99
/home/mohong/workspace/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.c: In function ‘crop_and_resize_forward’:
/home/mohong/workspace/pytorch-mask-rcnn/roialign/roi_align/src/crop_and_resize.c:124:33: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
     const int batch_size = image->size[0];
                                 ^~
Traceback (most recent call last):
  File "build.py", line 40, in <module>
    ffi.build()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/mohong/.local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/mohong/.local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/mohong/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/mohong/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
-----------------------------------------------------What I have do----------------------------------------------------------
And I install essentials,
sudo apt-get install python-dev  \
     build-essential libssl-dev libffi-dev \
     libxml2-dev libxslt1-dev zlib1g-dev \
     python-pip\
     libblas-dev libatlas-base-dev\

BUT, it still didn't work right. What's wrong with it? @tkepp @ozan-oktay @mattiaspaul @magzHL @ewoifjd 

-----------------------------------------------Environment----------------------------------------------------------------
Pythorch 0.4.1, CUDA 9.0, python 2.7, Linux 18.04

**Comment by qq4060** [comment]
I ALSO HAVE THIS PROBLEM...

**Comment by qq4060** [comment]
solved by this https://github.com/longcw/RoIAlign.pytorch/issues/11

**Comment by LaiPiXiong** [comment]
Thanks, I also try to downgrade 0.4.1 to 0.4.0
