### ISSUE TITLE
NMS without CUDA

### ISSUE THREAD

**Issue by kahya-se** [multimodallearning/pytorch-mask-rcnn#92]
Hello, I'd like to use Mask-RCNN in a CPU only mode. Yet still, the NMS module has to be installed using CUDA, which seems to me unnecessary, as I don't intend to use a GPU [for testing purposes on this machine]. Isn't it possible to run the model without CUDA (as it is possible in the tf-mask-rcnn)?

**Comment by kahya-se** [comment]
Duplicate to issue #15

**Comment by wangutian** [comment]
Have you solved the problem yet？
