### ISSUE TITLE
PyTorch 1.?

### ISSUE THREAD

**Issue by FiReTiTi** [multimodallearning/pytorch-mask-rcnn#96]
Hi,
is there an "easy" way to make it compatible with PyTorch 1 or later?
PyTorch 0.3 seems to be really outdated now.

**Comment by HelloDusty** [comment]
I am face to the same problem but switch the NMS and roialign to your own, the models going to run maybe. Now I am having a try.

**Comment by FiReTiTi** [comment]
I gave up on this one and used the TorchVision version, must better!

**Comment by shanniruo** [comment]
Did you succeed? I also want to use the rolalign module , by the way, do you know why NMS module and roialign module should be compiled by CUDA code?

**Comment by shanniruo** [comment]
@HelloDusty Did you succeed? I also want to use the rolalign module , by the way, do you know why NMS module and roialign module should be compiled by CUDA code?

**Comment by FiReTiTi** [comment]
@shanniruo I gave up on this one and used the TorchVision version, must better!

**Comment by shanniruo** [comment]
@FiReTiTi Sorry, I didn't understand. What should I do ？

**Comment by FiReTiTi** [comment]
@shanniruo: As the version in the current library does not seem to be supported anymore, I've switched to the TorchVision implementation.
There is now a Mask R-CNN implementation in PyTorch in the library TorchVision. It works really well and there is an example for pedestrian detection that can be easily modified for any applications.

**Comment by shanniruo** [comment]
@FiReTiTi tanks
